######################################################################
##
## Filename: ee201_numlock_sm_tb.udo
## Created on: Mon Oct 01 5:38:40 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
