######################################################################
##
## Filename: ee201_GCD_CEN_tb_v.udo
## Created on: Mon Oct 15 4:54:48 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
