######################################################################
##
## Filename: ee201_GCD_top.udo
## Created on: Mon Oct 15 5:47:39 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
