######################################################################
##
## Filename: ee201l_detour.udo
## Created on: Mon Sep 10 6:05:10 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
