######################################################################
##
## Filename: ee201l_detour_ee201l_detour_sch_tb.udo
## Created on: Mon Sep 10 5:58:38 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
