######################################################################
##
## Filename: merge_array_mcu_tb.udo
## Created on: Mon Oct 29 5:33:46 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
