######################################################################
##
## Filename: divider_tb.udo
## Created on: Mon Nov 05 5:32:55 PM Pacific Standard Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
